const Discord = require('discord.js');
const qdb = require('quick.db');
exports.run = async(client, message, args) => {
 if(!qdb.has(`dil_${message.guild.id}`)){ 
  var v11 = args.slice(0).join(' ')
  if(!v11) return message.channel.send(
  new Discord.MessageEmbed()
    .setColor('BLACK')
    .setAuthor(`${client.user.username} v11tov12 Sistemi`, client.user.displayAvatarURL({dynamic: true, format: "png"}))
    .setTitle(`${client.arez.hayırr} Başarısız!`)
    .setDescription(`${client.arez.ünlem} Bir kod belirtin!`)
  )
   if(v11.length > 1800) return message.channel.send(
     new Discord.MessageEmbed()
    .setColor('BLACK')
    .setAuthor(`${client.user.username} v11tov12 Sistemi`, client.user.displayAvatarURL({dynamic: true, format: "png"}))
    .setTitle(`${client.arez.hayırr} Başarısız!`)
    .setDescription(`${client.arez.ünlem} Yazdığınız kod **1800** karakterden uzun.`)
   )
  var v12 = v11
  .split('users.get')
  .join('users.cache.get')
  .split('channels.find')
  .join('channels.cache.find')
  .split('roles.find')
  .join('roles.cache.find')
  .split('message.get')
  .join('messages.cache.get')
  .split('users.exists')
  .join('users.cache.some')
  .split('forEach')
  .join('cache.forEach')
  .split('fetchUses')
  .join('users.fetch')
  .split('fetchMembers')
  .join('members.fetch')
  .split('fetchMessage')
  .join('messages.fetch')
  .split('fetchPinnedMessages')
  .join('messages.fetchPinned')
  .split('sendFile')
  .join('send({files["./Hello.png"]})')
  .split('sendEmbed')
  .join('send')
  .split('sendMessage')
  .join('send')
  .split('createRole')
  .join('roles.create')
  .split('addRole')
  .join('roles.add')
  .split('removeRole')
  .join('roles.remove')
  .split('highestRole')
  .join('roles.highest')
  .split('colorRole')
  .join('roles.color')
  .split('roles.get')
  .join('roles.cache.get')
  .split('avatarURL')
  .join('avatarURL()')
  .split('displayAvatarURL')
  .join('displayAvatarURL({dynamic: true, format: "png"})')
  .split('iconURL')
  .join('iconURL({dynamic: true, size: 1024"})')
  .split('RichEmbed')
  .join('MessageEmbed')
  .split('client.ping')
  .join('client.ws.ping')
  .split('client.uptime')
  .join('client.ws.uptime')
  .split('client.status')
  .join('client.ws.status')
  .split('voiceConnections')
  .join('voice.connections')
  
  return message.channel.send(
      new Discord.MessageEmbed()
    .setColor('BLACK')
    .setAuthor(`${client.user.username} v11tov12 Sistemi`, client.user.displayAvatarURL({dynamic: true, format: "png"}))
    .setTitle(`${client.arez.ok} Başarılı!`)
    .setDescription(`\`\`\`js\n${v12}\`\`\` `)
  )
 }
  else {
      var v11 = args.slice(0).join(' ')
  if(!v11) return message.channel.send(
  new Discord.MessageEmbed()
    .setColor('BLACK')
    .setAuthor(`${client.user.username} v11tov12 System`, client.user.displayAvatarURL({dynamic: true, format: "png"}))
    .setTitle(`${client.arez.hayırr} Unsuccesful!`)
    .setDescription(`${client.arez.ünlem} Specify a code!`)
  )
   if(v11.length > 1800) return message.channel.send(
     new Discord.MessageEmbed()
    .setColor('BLACK')
    .setAuthor(`${client.user.username} v11tov12 Sistemi`, client.user.displayAvatarURL({dynamic: true, format: "png"}))
    .setTitle(`${client.arez.hayırr} Unsuccesful!`)
    .setDescription(`${client.arez.ünlem} The code you wrote is longer than **1800** characters.`)
   )
  var v12 = v11
  .split('users.get')
  .join('users.cache.get')
  .split('channels.find')
  .join('channels.cache.find')
  .split('roles.find')
  .join('roles.cache.find')
  .split('message.get')
  .join('messages.cache.get')
  .split('users.exists')
  .join('users.cache.some')
  .split('forEach')
  .join('cache.forEach')
  .split('fetchUses')
  .join('users.fetch')
  .split('fetchMembers')
  .join('members.fetch')
  .split('fetchMessage')
  .join('messages.fetch')
  .split('fetchPinnedMessages')
  .join('messages.fetchPinned')
  .split('sendFile')
  .join('send({files["./Hello.png"]})')
  .split('sendEmbed')
  .join('send')
  .split('sendMessage')
  .join('send')
  .split('createRole')
  .join('roles.create')
  .split('addRole')
  .join('roles.add')
  .split('removeRole')
  .join('roles.remove')
  .split('highestRole')
  .join('roles.highest')
  .split('colorRole')
  .join('roles.color')
  .split('roles.get')
  .join('roles.cache.get')
  .split('avatarURL')
  .join('avatarURL()')
  .split('displayAvatarURL')
  .join('displayAvatarURL({dynamic: true, format: "png"})')
  .split('iconURL')
  .join('iconURL({dynamic: true, size: 1024"})')
  .split('RichEmbed')
  .join('MessageEmbed')
  .split('client.ping')
  .join('client.ws.ping')
  .split('client.uptime')
  .join('client.ws.uptime')
  .split('client.status')
  .join('client.ws.status')
  .split('voiceConnections')
  .join('voice.connections')
  
  return message.channel.send(
      new Discord.MessageEmbed()
    .setColor('BLACK')
    .setAuthor(`${client.user.username} v11tov12 System`, client.user.displayAvatarURL({dynamic: true, format: "png"}))
    .setTitle(`${client.arez.ok} Succesful!`)
    .setDescription(`\`\`\`js\n${v12}\`\`\` `)
  )
  }
 };
exports.conf = {
  aliases: [],
  permLevel: 0
}
exports.help = {
  name: "v11tov12"
}